Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -31,14 +31,22 @@ jobs:
           node-version: '18'
           registry-url: 'https://registry.npmjs.org'
 
+      - name: Check secret
+        env:
+          TOKEN: ${{ secrets.NPM_TOKEN }}
+        run: |
+          if [ -z "$TOKEN" ]; then
+          echo "Secret is missing!"
+            exit 1
+          else
+            echo "Secret is available (value hidden)"
+          fi
+
       - name: Install dependencies
         run: npm ci
 
       - name: Build all packages
         run: npm run build:all
-
-      - name: Print all environment variables
-        run: printenv
 
       - name: Verify npm authentication
         run: npm whoami
